services:
  frontend:
    working_dir: /srv/
    restart: "no"
    build:
      context: ./
      dockerfile: docker/dashboard/Dockerfile
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./dashboard:/srv:cached
    ports:
      - "9999:9999"
    command: sh -c "npm run dev"
  ratspeak:
    restart: "no"
    build:
      context: ./
      dockerfile: docker/ratspeak/Dockerfile
    environment:
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - RUST_BACKTRACE=full
      - DISPLAY=${DISPLAY}
      - CI=true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${XDG_RUNTIME_DIR:-/run/user/1000}/${WAYLAND_DISPLAY:-wayland-0}:${XDG_RUNTIME_DIR:-/run/user/1000}/${WAYLAND_DISPLAY:-wayland-0}:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./:/srv/ratspeak-src/Ratspeak:cached
      - ~/.local/share/:/root/.local/share/
    tty: true
    stdin_open: true
    network_mode: host
    working_dir: /srv/ratspeak-src/Ratspeak/src-tauri
    command: cargo tauri dev
