services:
  frontend:
    working_dir: /srv/
    restart: "no"
    build:
      context: ./
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./frontend:/srv:cached
    ports:
      - "9999:9999"
    command: sh -c "npm run dev"
    network_mode: host

  ratspeak:
    restart: "no"
    build:
      context: ./
      dockerfile: docker/ratspeak/Dockerfile
    environment:
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - RUST_BACKTRACE=full
      - DISPLAY=${DISPLAY}
      - WEBKIT_DISABLE_COMPOSITING_MODE=1
      - WEBKIT_DEBUG=1
      - CI=true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${XDG_RUNTIME_DIR:-/run/user/1000}/${WAYLAND_DISPLAY:-wayland-0}:${XDG_RUNTIME_DIR:-/run/user/1000}/${WAYLAND_DISPLAY:-wayland-0}:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./:/srv/ratspeak-src/Ratspeak:cached
      - ~/.local/share/:/root/.local/share/
    working_dir: /srv/ratspeak-src/Ratspeak/src-tauri
    command: cargo tauri dev
    network_mode: host
    stdin_open: true
    tty: true
    depends_on:
      - frontend
